/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.mobilejourney.kata

class App {

}

fun main() {
    println("=============runK1==============")
    runK1()
    println("=============runK2==============")
    runK2()
    println("=============runK3==============")
    runK3()
    println("=============runK4==============")
    runK4()
    println("=============runK5==============")
    runK5()
//    println(Modifier.weight(1f))
//    IDE của tôi lỗi không tìm thấy .weight
}
